@api = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJydWxpcHBpQGdtYWlsLmNvbSIsInVzZXJJRCI6IjYyOTdjMDA3ODNlYzA5NTJiODBlYjgwMyIsImlhdCI6MTY1NDExMjI3NCwiZXhwIjoxNjU0MTE1ODc0fQ.4f5-E3ghuoH8BO6UmKJTFzcdqGf9TOA_H6ONcmxHfps

### Crear usuario
POST {{api}}/api/login/createUser
Content-Type: application/json

{
    "username": "brulippi@gmail.com",
    "password": "1234",
    "name": "Bruno",
    "surname": "Lippi"
}

### Existe usuario
GET {{api}}/api/login/existUser
Content-Type: application/json

{
    "username": "natafridman4",
    "password": "Nata123!"
}

### Ver todos los usuarios
GET {{api}}/api/login/getAllUsers
Authorization: {{token}}

### Login
POST {{api}}/api/login
Content-Type: application/json

{
    "username": "brulippi@gmail.com",
    "password": "1234"
}

### Update User
PUT {{api}}/api/login/updateUser/628d28b1e2996c7896651f31
Content-Type: application/json
Authorization: {{token}}

{
    "role": "admin"
}

### Delete User
DELETE {{api}}/api/login/deleteUser/628d28e1396599a0e33438a8
Content-Type: application/json
Authorization: {{token}}

### Crear post
POST {{api}}/api/post/createPost
Content-Type: application/json
Authorization: {{token}}

{
    "created_by": "628d22a3fe831e5c09e1756f",
    "description": "hola mundo, este es mi post 8"
}

### Ver todos los posts
GET {{api}}/api/post/getAllPosts?withComments=true
Authorization: {{token}}

### Likear post
PUT {{api}}/api/post/likePost/6290f7509a51ab1eb598de52
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hdGFmcmlkbWFuNCIsInVzZXJJRCI6IjYyOGQyN2Y0MDIyNmQyMWI1MTIwZTM3OSIsImlhdCI6MTY1MzY2NTY0NCwiZXhwIjoxNjUzNjY5MjQ0fQ.bd0H0mII7Tz_J22W1hC7Ka3KyKQQLeZ6mXRo1Eiiqs0

### Crear comentario de un post
POST {{api}}/api/comment/createComment/629667a6975a830205e8b281
Content-Type: application/json
Authorization: {{token}}

{
    "created_by": "628d22a3fe831e5c09e1756f",
    "description": "este es un comentario"
}

### Ver todos los comentarios
GET {{api}}/api/comment/getAllComments
Authorization: {{token}}